### ISSUE TITLE
Got an TypeError: Cannot read property 'length' of undefined at emitData (...../node_modules/strtok2/lib/index.js:369:54)

### ISSUE THREAD

**Issue by dready92** [Borewit/strtok2#3]
Hello there,

first, let me say that I have no clue what this (certainly wonderful) library does, I use it through "through" itself used by "nodemetadata". Whatever, I got an edge case where the error in this issue title is raised.

Out of curiosity I logged just before that line : 

    console.log('strtok2, bufs: ', bufs.length, type.len, bufsLen);

and here is what I got:

```
strtok2, bufs:  1 27 15149
strtok2, bufs:  1 23 15122
strtok2, bufs:  1 5192 15099
strtok2, bufs:  1 27 9907
strtok2, bufs:  1 39 9880
strtok2, bufs:  1 9014 9841
strtok2, bufs:  1 27 827
strtok2, bufs:  1 5 800
strtok2, bufs:  1 767 795
strtok2, bufs:  1 27 28
strtok2, bufs:  1 1 1
strtok2, bufs:  0 0 0
TypeError: Cannot read property 'length' of undefined
```

I know that kind of bug reports, without clear reproduction steps, are kind of complicated to handle, however it smells the unhandled special case where everything is equal to 0, but still passes the 

    while (type !== DONE && type !== DEFER && bufsLen >= type.len) {

Another info, I'm running node v6.5.0.

**Comment by Borewit** [comment]
Cannot reproduce this issue.
I recommend to use [music-metadata](https://www.npmjs.com/package/music-metadata) instead.
